title: Coupled Wave Theory of Distributed Feedback Lasers
author: Jan Genoe, Iakov Goldberg, Nirav Annavarapu, Simon Leitner, Robert Gehlhaar
logo: images/logo.png
description: calculations of distributed feedback lasers based on coupled wave theory
only_build_toc_files: true
repository:
  url: https://github.com/jangenoe/Coupled-Wave-Theory_DFB-Lasers
html:
  use_issues_button: true
  use_edit_page_button: true
  use_repository_button: true
execute:
  execute_notebooks: "off"
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist
bibtex_bibfiles:
  - DFB.bib
sphinx:
  config:
    html_show_copyright: false
    nb_remove_code_source: true
    latex_logo: images/logo.png
    latex_elements:
      extraclassoptions: 'openany,oneside'
      papersize: 'a4paper'
      preamble: |+
        \usepackage{etoolbox}
        \AtBeginEnvironment{figure}{\pretocmd{\hyperlink}{\protect}{}{}}  
    bibtex_reference_style: label
    bibtex_default_style : "unsrt"

