name: deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r .github/requirements-Book.txt
        sudo apt-get install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk
    - name: Build the Jupyterbook website
      run: |
        jb build ./
        jb build ./ --builder pdflatex
        mv ./_build/latex/python.pdf ./_build/html/Coupled-Wave-Theory_DFB-Lasers.pdf
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        
  build-jupyter-lite:
    needs: build-and-deploy-book
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install the dependencies
      run: |
        pip install -r .github/requirements-Lite.txt
    - name: Build the JupyterLite site
      run: |
        jupyter lite build --lite-dir Lite  --output-dir dist/
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: Lite